In [1]:
import csv


with open('/content/p2p-Gnutella04.txt', 'r') as input_file:
    with open('output1.csv', 'w', newline='') as output_file:
        csv_writer = csv.writer(output_file)
        csv_writer.writerow(['FromNodeId', 'ToNodeId'])
        for line in input_file:
            values = line.strip().split('\t')
            if(len(values)==1):
              continue
            csv_writer.writerow([values[0], values[1]])

In [2]:
import pandas as pd
import numpy as np

In [3]:
import csv
with open('output1.csv', 'r') as f_in:
    reader = csv.reader(f_in)
    rows = list(reader)
    rows.pop(0)

with open('output1.csv', 'w', newline='') as f_out:
    writer = csv.writer(f_out)
    writer.writerows(rows)

In [4]:
col_names=['FromNodeId','ToNodeId'] 
df=pd.read_csv("output1.csv",names=col_names)

df=df[1:]
df.head(15)

FromNodeId ToNodeId
1           0        1
2           0        2
3           0        3
4           0        4
5           0        5
6           0        6
7           0        7
8           0        8
9           0        9
10          0       10
11          1        2
12          1       11
13          1       12
14          1       13
15          1       14

In [5]:
#selecting the unique node set
unique_nodes= len(set(df['FromNodeId']).union(set(df['ToNodeId'])))

In [6]:
#printing the number of unique nodes
unique_nodes

10876

In [7]:
#finding the values of unique nodes and storing in an array
unique_nodes = np.unique(df[["FromNodeId", "ToNodeId"]].values.tolist())
unique_nodes

array(['0', '1', '10', ..., '9997', '9998', '9999'], dtype='<U5')

In [8]:
len(unique_nodes)

10876

In [9]:
#converting into a datframe
testing =pd.DataFrame(0,columns = unique_nodes,index = unique_nodes)

In [10]:
testing

0  1  10  100  1000  10000  10001  10002  10003  10004  ...  9990  9991  \
0     0  0   0    0     0      0      0      0      0      0  ...     0     0   
1     0  0   0    0     0      0      0      0      0      0  ...     0     0   
10    0  0   0    0     0      0      0      0      0      0  ...     0     0   
100   0  0   0    0     0      0      0      0      0      0  ...     0     0   
1000  0  0   0    0     0      0      0      0      0      0  ...     0     0   
...  .. ..  ..  ...   ...    ...    ...    ...    ...    ...  ...   ...   ...   
9995  0  0   0    0     0      0      0      0      0      0  ...     0     0   
9996  0  0   0    0     0      0      0      0      0      0  ...     0     0   
9997  0  0   0    0     0      0      0      0      0      0  ...     0     0   
9998  0  0   0    0     0      0      0      0      0      0  ...     0     0   
9999  0  0   0    0     0      0      0      0      0      0  ...     0     0   

      9992  9993  9994  9995  9996  9997  9998  9999  
0        0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0  
10       0     0     0     0     0     0     0     0  
100      0     0     0     0     0     0     0     0  
1000     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...  
9995     0     0     0     0     0     0     0     0  
9996     0     0     0     0     0     0     0     0  
9997     0     0     0     0     0     0     0     0  
9998     0     0     0     0     0     0     0     0  
9999     0     0     0     0     0     0     0     0  

[10876 rows x 10876 columns]

In [11]:
#making the adjacency matrix 
num_nodes = len(unique_nodes)
adj_matrix = np.zeros((num_nodes+3, num_nodes+3))
print(adj_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [12]:
for index, row in df.iterrows():
    fr_row=int(row["FromNodeId"])
    # fr.append(fr_row)
    to_row=int(row["ToNodeId"])
    # to.append(to_row)
    adj_matrix[fr_row][to_row]=1

In [13]:
#this is the adjacency matrix
adj_matrix

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
df2=pd.DataFrame(adj_matrix)

In [15]:
df2 = df2.astype(int)
df2

0      1      2      3      4      5      6      7      8      9      \
0          0      1      1      1      1      1      1      1      1      1   
1          0      0      1      0      0      0      0      0      0      0   
2          0      0      0      0      0      0      0      0      0      0   
3          0      0      0      0      0      0      0      0      0      0   
4          0      0      0      0      0      0      0      0      0      0   
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
10874      0      0      0      0      0      0      0      0      0      0   
10875      0      0      0      0      0      0      0      0      0      0   
10876      0      0      0      0      0      0      0      0      0      0   
10877      0      0      0      0      0      0      0      0      0      0   
10878      0      0      0      0      0      0      0      0      0      0   

       ...  10869  10870  10871  10872  10873  10874  10875  10876  10877  \
0      ...      0      0      0      0      0      0      0      0      0   
1      ...      0      0      0      0      0      0      0      0      0   
2      ...      0      0      0      0      0      0      0      0      0   
3      ...      0      0      0      0      0      0      0      0      0   
4      ...      0      0      0      0      0      0      0      0      0   
...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
10874  ...      0      0      0      0      0      0      1      1      0   
10875  ...      0      0      0      0      0      0      0      0      0   
10876  ...      0      0      0      0      0      0      0      0      0   
10877  ...      0      0      0      0      0      0      0      0      0   
10878  ...      0      0      0      0      0      0      0      0      0   

       10878  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
10874      0  
10875      0  
10876      0  
10877      0  
10878      0  

[10879 rows x 10879 columns]

In [16]:
num_nodes = len(unique_nodes)
A = np.zeros((num_nodes, num_nodes))
for row in df.itertuples():
    testing.at[row.FromNodeId,row.ToNodeId] = 1
    
print("Weighted directed Adjacency Matrix in dataframe" + "\n")
testing

Weighted directed Adjacency Matrix in dataframe



0  1  10  100  1000  10000  10001  10002  10003  10004  ...  9990  9991  \
0     0  1   1    0     0      0      0      0      0      0  ...     0     0   
1     0  0   0    0     0      0      0      0      0      0  ...     0     0   
10    0  0   0    0     0      0      0      0      0      0  ...     0     0   
100   0  0   0    0     0      0      0      0      0      0  ...     0     0   
1000  0  0   0    0     0      0      0      0      0      0  ...     0     0   
...  .. ..  ..  ...   ...    ...    ...    ...    ...    ...  ...   ...   ...   
9995  0  0   0    0     0      0      0      0      0      0  ...     0     0   
9996  0  0   0    0     0      0      0      0      0      0  ...     0     0   
9997  0  0   0    0     0      0      0      0      0      0  ...     0     0   
9998  0  0   0    0     0      0      0      0      0      0  ...     0     0   
9999  0  0   0    0     0      0      0      0      0      0  ...     0     0   

      9992  9993  9994  9995  9996  9997  9998  9999  
0        0     0     0     0     0     0     0     0  
1        0     0     0     0     0     0     0     0  
10       0     0     0     0     0     0     0     0  
100      0     0     0     0     0     0     0     0  
1000     0     0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...   ...  
9995     0     0     0     0     0     0     0     0  
9996     0     0     0     0     0     0     0     0  
9997     0     0     0     0     0     0     0     0  
9998     0     0     0     0     0     0     0     0  
9999     0     0     0     0     0     0     0     0  

[10876 rows x 10876 columns]

In [17]:
#finding edhge list
edge_list=[]
for index,row in df.iterrows():
    temp_list=[]
    temp_list.append(row["FromNodeId"])
    temp_list.append(row["ToNodeId"])
    edge_list.append(temp_list)

In [18]:
#printing the edge list
edge_list

[['0', '1'],
 ['0', '2'],
 ['0', '3'],
 ['0', '4'],
 ['0', '5'],
 ['0', '6'],
 ['0', '7'],
 ['0', '8'],
 ['0', '9'],
 ['0', '10'],
 ['1', '2'],
 ['1', '11'],
 ['1', '12'],
 ['1', '13'],
 ['1', '14'],
 ['1', '15'],
 ['1', '16'],
 ['1', '17'],
 ['1', '18'],
 ['1', '19'],
 ['3', '20'],
 ['3', '21'],
 ['3', '22'],
 ['3', '23'],
 ['3', '24'],
 ['3', '25'],
 ['3', '26'],
 ['3', '27'],
 ['3', '28'],
 ['3', '29'],
 ['8', '30'],
 ['8', '31'],
 ['8', '32'],
 ['8', '33'],
 ['8', '34'],
 ['8', '35'],
 ['8', '36'],
 ['8', '37'],
 ['8', '38'],
 ['8', '39'],
 ['10', '41'],
 ['10', '136'],
 ['10', '137'],
 ['10', '138'],
 ['10', '139'],
 ['10', '140'],
 ['10', '141'],
 ['10', '142'],
 ['10', '143'],
 ['10', '144'],
 ['12', '40'],
 ['12', '41'],
 ['12', '42'],
 ['12', '43'],
 ['12', '44'],
 ['12', '45'],
 ['12', '46'],
 ['12', '47'],
 ['12', '48'],
 ['12', '49'],
 ['14', '199'],
 ['14', '756'],
 ['14', '1116'],
 ['14', '2537'],
 ['14', '2787'],
 ['14', '3307'],
 ['14', '4524'],
 ['14', '4674'],
 ['14',

In [19]:
no_of_edge=len(edge_list)

In [20]:
#number of nodes
print("number of nodes -> ",len(np.unique(unique_nodes)))

number of nodes ->  10876


In [21]:
#length of edge_list
print("count of edges-> ",len(edge_list))

count of edges->  39994


In [22]:
# code for finding average in degree
in_degrees = np.sum(adj_matrix, axis=1)
avg_in_deg = np.mean(in_degrees)
print("average in degree", avg_in_deg)


average in degree 3.6762570089162607


In [23]:
#code for finding average out degree
out_degrees = np.sum(adj_matrix, axis=0)
avg_out_deg = np.mean(out_degrees)
print("Average Out-Degree of Network:", avg_out_deg)

Average Out-Degree of Network: 3.6762570089162607


In [24]:
#code for finding node with maximum out degree
out_dict={}
max_degree = 0
max_node = -1
for i in range(len(adj_matrix)):
    outdegree = sum(adj_matrix[i])
    out_dict[i]=outdegree
    if outdegree > max_degree:
        max_degree = outdegree
        max_node = i
print("node with max out degree",max_node,int(max_degree))



node with max out degree 3109 100


In [25]:
#code for finding node with maximum in degree
in_dict={}
max_in_degree=0
max_out_node=-1
for i in range (len(adj_matrix[0])):
  count=0
  for j in range(len(adj_matrix)):
    if (adj_matrix[j][i]==1):
      count+=1
  in_dict[i]=count
  if (count>max_in_degree):
    max_in_degree=count
    max_out_node=i
print("node with max in degree",max_out_node,int(max_in_degree))

    
    



node with max in degree 1054 72


In [26]:
#code for finding the density of matrix
print("density of the network", no_of_edge/(len(unique_nodes)*(len(unique_nodes)-1)))

density of the network 0.0003381398671756435
